In [ ]:
%load_ext autoreload
%autoreload 2

In [7]:
from solutions import sigmoid, sigmoid_jac, softmax, softmax_jac, MSE, MSE_grad, densa_forward, forward, get_gradients
import numpy as np

In [3]:
weights = np.load('weights_softmax_3_layers.npy', allow_pickle=True)

In [68]:
X = np.array([[1, 1], [-2, 1], [-3, 2], [-3, -2], [-3, -2]])
P_true = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1]])

# X = np.array([[1, 1]])
# P_true = np.array([[1, 0, 0]])

In [80]:
sm = softmax(D3_out)
print(sm)

[[0.36967761 0.1476544  0.48266799]
 [0.36363375 0.15044378 0.48592246]
 [0.36568368 0.14989345 0.48442287]
 [0.35234444 0.15479326 0.4928623 ]
 [0.35234444 0.15479326 0.4928623 ]]


In [131]:
np.tensordot(sm.T, sm, axes=1)

array([[0.65090881, 0.27318564, 0.87958948],
       [0.27318564, 0.11482511, 0.36956741],
       [0.87958948, 0.36956741, 1.18958103]])

In [110]:
sm[,:].T.dot(sm[0,:])

0.39143174464451624

In [116]:
sm[:,0].shape

(5,)

In [70]:
def softmax_jac(Xin):
    sm = softmax(Xin)
    return np.diag(sm.reshape(-1)) - sm.reshape(-1, 1).dot(sm.reshape(1, -1))

In [71]:
P_est, loss, D1_in, D2_in, D3_in = forward(X, P_true, weights)
MSE_grad_out = MSE_grad(P_true, P_est)
print(P_est)
print(mse)
print(MSE_grad_out)
D3_out = D3_in.dot(weights[4]) + weights[5]
sm_jac = softmax_jac(D3_out)
print(sm_jac.shape)

# error_D3 = softmax_jac(D3_in.dot(weights[4]) + weights[5]).dot(MSE_grad_out)

(5,)
[[0.36967761 0.1476544  0.48266799]
 [0.36363375 0.15044378 0.48592246]
 [0.36568368 0.14989345 0.48442287]
 [0.35234444 0.15479326 0.4928623 ]
 [0.35234444 0.15479326 0.4928623 ]]
0.2401951391383135
[ 0.10715786 -0.03232291 -0.07483494]
(5,)
(15, 15)


In [51]:
X.shape, P_true.shape, MSE_grad_out.shape

((3, 2), (3, 3), (3,))

In [52]:
def get_updated_ws(weights, lr = 0.1):
    grads, loss = get_gradients(X, P_true, weights)
    new_w = []
    for i, w in enumerate(weights):
        new_w.append(w - lr*grads[i])
    return new_w, loss

new_w, loss = get_updated_ws(weights)
print(loss)
for i in range(50):
    new_w, loss = get_updated_ws(new_w)
    print(loss)

ValueError: shapes (9,9) and (3,) not aligned: 9 (dim 1) != 3 (dim 0)